### ISSUE TITLE
module not working in certain position

### ISSUE THREAD

**Issue by keyworthgraphics** [betweenbrain/jFontSize-Module#18] opened 2015-01-06 00:59 UTC
hi there,

can someone help me figure this out?
here's an example: http://biavt.org/beta2/index.php/learn-more/adrc 
when i change module position to the bottom it works.

thank you,
will

**Comment by betweenbrain** [comment] 2015-01-06 11:29
Can you please provide more information such as what you’ve tried, expected and actual results...etc.

**Comment by keyworthgraphics** [comment] 2015-01-06 19:38
in the upper module position it does not work, as far as being clickable to enlarge the font size, but if i move it to a module lower on the page, it does work meaning the text increases/decreases as it should not sure what the conflict is?

**Comment by betweenbrain** [comment] 2015-01-07 00:19
If you can publish an two instances of the module, one to each position, I can take a look and see if I can identify the issue. I can't make any promises, but will see if something jumps out at me.

**Comment by keyworthgraphics** [comment] 2015-01-07 03:15
thanks so much. here's the page i have the module published in two places:
http://biavt.org/beta2/index.php/coping-with-tbi/neuro-resource - the one that works is below the search module in the bottom-a position.

**Comment by betweenbrain** [comment] 2015-01-08 04:52
You're very welcome. The issue is caused because `rt-grid-12 rt-alpha rt-omega` is overlapping the area where the module is located. Please see attached. I'd suggest modifying some of the CSS to move the module down slightly as `rt-grid-12 rt-alpha rt-omega` is part of the floating navigation.
![screenshot - 01072015 - 11 48 32 pm](https://cloud.githubusercontent.com/assets/634119/5658026/13df46fe-96c8-11e4-9e29-d928afc2dce2.png)
hed.

**Comment by keyworthgraphics** [comment] 2015-01-09 04:15
thanks. is there a way for the font resizer to as a plugin snippet in an article?

**Comment by keyworthgraphics** [comment] 2015-01-09 12:35
thanks again for your time! happy new year

**Comment by betweenbrain** [comment] 2015-01-09 12:58
You're very welcome! Happy New Year to you too.

I'm closing this issue, but feel free to open another if you have other questions or problems.

**Closed by betweenbrain** 2015-01-09 12:58 UTC
